[package]
name = "sqnc"
version = "1.0.0-dev"
authors = ["Evalf <info@evalf.com>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/evalf/sqnc"
description = "Sequence"
keywords = ["sequence", "no_std"]
rust-version = "1.64"

[features]
alloc = []

[dependencies]
ndarray = { version = "0.15", optional = true }

[package.metadata.docs.rs]
all-features = true
